"use client";

import { useEffect, useState } from "react";
import { supabase } from "@/lib/supabase";
import Link from "next/link";

type Result={domain:string;score:string;sslValid:boolean;httpsRedirect:boolean;scanId:string|null};
export default function EnglishScanner(){const[userId,setUserId]=useState("");const[url,setUrl]=useState("");const[owner,setOwner]=useState(false);const[loading,setLoading]=useState(false);const[result,setResult]=useState<Result|null>(null);const[error,setError]=useState("");useEffect(()=>{supabase.auth.getUser().then(({data})=>data.user&&setUserId(data.user.id))},[]);async function scan(){setLoading(true);setError("");setResult(null);try{const r=await fetch("/api/scan",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({url,userId})});const d=await r.json();if(d.error)setError(d.error);else setResult(d)}catch{setError("Scan failed. Please try again.")}finally{setLoading(false)}}return <div className="es"><span className="kicker">SECURITY SCANNER</span><h1>Scan your SaaS.</h1><p className="sub">Check the security signals visible from the outside, then open the full report.</p><div className="card"><div className="terminal"><i/><i/><i/><span>lokky — scanner</span></div><div className="input"><b>$ scan</b><input value={url} onChange={e=>setUrl(e.target.value)} onKeyDown={e=>e.key==="Enter"&&owner&&url&&!loading&&scan()} placeholder="my-saas.com"/></div><label><input type="checkbox" checked={owner} onChange={e=>setOwner(e.target.checked)}/> I confirm I own this domain or have permission to scan it.</label><button onClick={scan} disabled={loading||!url||!owner}>{loading?"Scanning…":"Run security scan →"}</button>{error&&<p className="error">✗ {error}</p>}</div>{result&&<section className="result"><div><small>SECURITY SCORE</small><strong>{result.score}</strong><h2>{result.domain}</h2></div><div className="checks"><p><span className={result.sslValid?"ok":"bad"}>{result.sslValid?"✓":"✗"}</span> SSL certificate</p><p><span className={result.httpsRedirect?"ok":"bad"}>{result.httpsRedirect?"✓":"✗"}</span> HTTPS redirect</p></div>{result.scanId&&<Link href={`/report/${result.scanId}`}>Open full report →</Link>}</section>}
  <style jsx>{`.es{max-width:760px;color:#f8fafc;font-family:Inter,Arial,sans-serif}.kicker{font:600 10px ui-monospace;color:#a855f7;letter-spacing:.15em}.es h1{font-size:38px;letter-spacing:-.04em;margin:12px 0 8px}.sub{font-size:14px;color:#858091;margin:0 0 30px}.card,.result{background:#0d0a13;border:1px solid rgba(255,255,255,.08);border-radius:15px;padding:22px}.terminal{display:flex;align-items:center;gap:6px;margin-bottom:20px}.terminal i{width:7px;height:7px;border-radius:50%;background:#ef4444}.terminal i:nth-child(2){background:#f59e0b}.terminal i:nth-child(3){background:#22c55e}.terminal span{font:9px ui-monospace;color:#475569;margin-left:5px}.input{display:flex;gap:10px;align-items:center}.input b{font:11px ui-monospace;color:#a855f7}.input input{flex:1;background:#09070d;border:1px solid rgba(255,255,255,.09);color:#fff;border-radius:8px;padding:11px;font:12px ui-monospace;outline:none}.card label{display:flex;gap:9px;align-items:flex-start;margin:15px 0;color:#64748b;font-size:11px;line-height:1.5}.card label input{margin-top:2px;accent-color:#8b5cf6}.card>button{background:#8b5cf6;color:#fff;border:0;border-radius:8px;padding:11px 15px;font-size:12px;font-weight:600;cursor:pointer}.card>button:disabled{opacity:.45}.error{color:#ef4444;font:11px ui-monospace;margin-bottom:0}.result{margin-top:18px;display:grid;grid-template-columns:1fr 1fr;gap:20px;align-items:center}.result small{display:block;font:600 9px ui-monospace;color:#64748b}.result strong{display:block;font-size:42px;color:#a855f7;margin:5px 0}.result h2{font-size:14px;margin:0}.checks{border-left:1px solid rgba(255,255,255,.07);padding-left:20px}.checks p{font-size:12px;color:#cbd5e1}.checks span{margin-right:8px}.ok{color:#22c55e}.bad{color:#ef4444}.result>a{grid-column:1/-1;color:#c4b5fd;text-decoration:none;font-size:11px;border-top:1px solid rgba(255,255,255,.06);padding-top:16px}@media(max-width:600px){.es h1{font-size:30px}.result{grid-template-columns:1fr}.checks{border-left:0;padding-left:0}}`}</style></div>}
