import { NextRequest, NextResponse } from "next/server";

type Issue={label:string;impact:string};type ChatMessage={role:"user"|"assistant";text:string};
const stacks=["Next.js","NextJS","React","Node.js","Node","Supabase","Vercel","Firebase","Prisma","PostgreSQL","Postgres","MongoDB","Mongo","Express","Laravel","Django","Python","TypeScript","JavaScript","Tailwind","Cloudflare","Netlify","AWS","Stripe","Lovable","Bolt","Cursor","Claude Code"];
const extract=(text:string)=>stacks.filter(s=>text.toLowerCase().includes(s.toLowerCase())).filter((s,i,a)=>a.indexOf(s)===i);
const fallback=(message:string,issues:Issue[],history:ChatMessage[],locale:"fr"|"en")=>{const en=locale==="en",lower=message.toLowerCase(),issue=issues[0],all=[...new Set([...history.flatMap(m=>extract(m.text)),...extract(message)])],stack=all.length?all.join(" + "):(en?"your current stack":"ton stack actuel");const context=all.length?(en?`I'll keep your stack in context: ${stack}.`:`Je garde ton stack en mémoire : ${stack}.`):(en?"Tell me your stack, for example Next.js + Supabase + Vercel.":"Donne-moi ton stack, par exemple Next.js + Supabase + Vercel.");
 if(lower.includes("cursor")||lower.includes("prompt"))return en?`Here is a Cursor prompt for ${stack}:\n\nYou are working on my ${stack} application. Lokky detected “${issue?.label??"a security issue"}”. Analyze the project, explain the root cause briefly, then apply the safest simple fix without breaking existing functionality. Verify the fix before finishing.\n\n${issue?.impact?`Context: ${issue.impact}\n\n`:""}Then return to Lokky and re-scan my SaaS.`:`Voici un prompt prêt à copier dans Cursor pour ${stack} :\n\nTu travailles sur mon application ${stack}. Lokky a détecté « ${issue?.label??"un problème de sécurité"} ». Analyse le projet, explique brièvement la cause, puis applique la correction la plus simple et sûre sans casser l'existant. Vérifie la correction avant de terminer.\n\n${issue?.impact?`Contexte : ${issue.impact}\n\n`:""}Une fois terminé, reviens dans Lokky et re-scanne mon SaaS.`;
 if(all.length||lower.includes("stack"))return en?`Got it. ${context}\n\nThe priority issue is “${issue?.label??"the detected issue"}”. ${issue?.impact??"It should be reviewed before production."}`:`Oui, j'ai compris ton environnement. ${context}\n\nLe problème prioritaire est « ${issue?.label??"le problème détecté"} ». ${issue?.impact??"Il mérite d'être corrigé avant la mise en production."}`;
 return en?`I can help you fix “${issue?.label??"your security issue"}” without jargon. ${context}`:`Je peux t'aider à corriger « ${issue?.label??"ton problème de sécurité"} » sans jargon. ${context}`;};

export async function POST(request:NextRequest){try{const{domain,score,issues=[],message,history=[],locale="fr"}=await request.json();if(typeof message!=="string"||!message.trim())return NextResponse.json({error:locale==="en"?"Missing message":"Message manquant"},{status:400});const key=process.env.OPENAI_API_KEY;if(!key)return NextResponse.json({reply:fallback(message,issues,history,locale)});const context=issues.map((i:Issue)=>`- ${i.label}: ${i.impact}`).join("\n"),conversation=history.slice(-10).map((m:ChatMessage)=>({role:m.role==="user"?"user":"assistant",content:m.text})),en=locale==="en";const system=`You are Lokky Assistant, a security copilot for non-expert SaaS makers. ${en?"Reply in English":"Réponds en français"}, simply and without unnecessary jargon. Remember the user's stack throughout the conversation. Never ask again for information already provided. You can explain, give short steps and provide prompts for Cursor or Claude Code. Never claim access to code that was not provided. Never request or expose secrets, passwords or private keys. Never provide offensive procedures against third parties. Scan context: domain=${domain}, score=${score}. Issues:\n${context||"none"}`;const response=await fetch("https://api.openai.com/v1/chat/completions",{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${key}`},body:JSON.stringify({model:process.env.OPENAI_MODEL||"gpt-4o-mini",temperature:.2,max_tokens:900,messages:[{role:"system",content:system},...conversation,{role:"user",content:message.trim()}]})});const data=await response.json();if(!response.ok)return NextResponse.json({reply:fallback(message,issues,history,locale)});return NextResponse.json({reply:data.choices?.[0]?.message?.content||fallback(message,issues,history,locale)});}catch{return NextResponse.json({reply:"I can help you fix this. Tell me your stack and what you want to do."})}}
